- name: Export MikroTik Router Configuration
  hosts: Switches01
  gather_facts: no
  tasks:
    - name: Ping the MikroTik router
      ansible.builtin.ping:

    - name: Export configuration to a file on the router
      ansible.netcommon.cli_command:
        command: /export file=my-config
      register: export_result

    - name: Verify export command success
      debug:
        var: export_result.stdout

    - name: Fetch the configuration file from the router
      ansible.builtin.fetch:
        src: my-config.rsc
        dest: ./router-configs/
        flat: yes

    - name: Confirm file fetch
      debug:
        msg: "Configuration file fetched successfully to ./router-configs/my-config.rsc"
